"use strict";
exports.__esModule = true;
var Container_1 = require("./Container");
exports.Container = Container_1["default"];
var Header_1 = require("./Header");
exports.Header = Header_1["default"];
var Main_1 = require("./Main");
exports.Main = Main_1["default"];
var Footer_1 = require("./Footer");
exports.Footer = Footer_1["default"];
